name: Enviar Correos de Recordatorio

on:
  schedule:
    - cron: '30 7 * * *' # Ejecutar a las 7:30 AM todos los días
  workflow_dispatch: # Habilita la ejecución manual

jobs:
  correos-recordatorio:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set environment variables
      env:
        USUARIO_CORREO_JURIDICO: ${{ secrets.USUARIO_CORREO_JURIDICO }}
        CLAVE_CORREO_JURIDICO: ${{ secrets.CLAVE_CORREO_JURIDICO }}
        DATABASE_PATH: ${{ secrets.DATABASE_PATH }}
      run: echo "Environment variables set."

    - name: Enviar correos de recordatorio
      run: |
        python -c "from jobs import TareasProgramadasJuridico; TareasProgramadasJuridico().tarea_diaria_recordatorio()"
