name: Sincronizar Estados

on:
  schedule:
    - cron: '0 8 * * *' # 3:00 AM Bogot치 (8:00 AM UTC)
  workflow_dispatch: # Habilita la ejecuci칩n manual

jobs:
  sincronizar-estados:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verificar conexi칩n a la base de datos
      env:
        DATABASE_PATH: ${{ secrets.DATABASE_PATH }}
      run: |
        python -c "
        import psycopg2
        try:
            conn = psycopg2.connect('${{ secrets.DATABASE_PATH }}')
            print('Conexi칩n a la base de datos exitosa')
            conn.close()
        except Exception as e:
            print(f'Error al conectar a la base de datos: {e}')
            raise e
        "

    - name: Sincronizar estados
      env:
        DATABASE_PATH: ${{ secrets.DATABASE_PATH }}
        USUARIO_CORREO_JURIDICO: ${{ secrets.USUARIO_CORREO_JURIDICO }}
        CLAVE_CORREO_JURIDICO: ${{ secrets.CLAVE_CORREO_JURIDICO }}
      run: |
        python -c "from model.job import TareasProgramadasJuridico; TareasProgramadasJuridico().sincronizar_estados_filas_gestion()"

