name: Sincronización de Estados

on:
  schedule:
    - cron: '0 3 * * *' # Ejecutar a las 3:00 AM todos los días

jobs:
  sincronizar-estados:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set environment variables
      env:
        USUARIO_CORREO_JURIDICO: ${{ secrets.USUARIO_CORREO_JURIDICO }}
        CLAVE_CORREO_JURIDICO: ${{ secrets.CLAVE_CORREO_JURIDICO }}
        DATABASE_PATH: ${{ secrets.DATABASE_PATH }}
      run: echo "Environment variables set."

    - name: Ejecutar sincronización de estados
      run: |
        python -c "from jobs import TareasProgramadasJuridico; TareasProgramadasJuridico().sincronizar_estados_filas_gestion()"
